### ISSUE TITLE
✅ 11:45 〜 wartremoverのScala 3対応

### ISSUE THREAD

**Issue by xuwei-k** [scalamatsuri/2022.open-mic-conference#13]
[wartremover](https://github.com/wartremover/wartremover) というScalaのcompiler pluginがあるのですが、それのScala 3対応を最近やり始めたので、それの話が多少できるかもしれません。

ただでさえ(Scala 2の)compiler pluginの情報は少ないのに、さらにScala 3でのcompiler pluginの情報は少なかったり、
compiler pluginなのでScala 2とは一切互換がなく、原理上全て書き直しになるのですが、それにあたって色々工夫した点や、辛かった点、scalafixとの比較などについて、話せたら話したい。

資料はこのissue作成時点で全く作ってないので、もしやるならば、発表は出来るだけ後の方がいいかも・・・

**Comment by taketora26** [comment]
30 ~ 45分

**Comment by xuwei-k** [comment]
資料: https://xuwei-k.github.io/slides/wartremover-3/#1
